volunteers/urls.py
from django.conf.urls import patterns, include, url
from volunteers import views

urlpatterns = patterns('',
    #url(r'^$', views.index, name='volunteer_index'),
    #url(r'^(?P<volunteer_id>\d+)/$', views.volunteer_detail, name='volunteer_detail'),
    #url(r'^AddTasks/$', views.add_tasks, name='add_tasks'),
    #url(r'^(?P<volunteer_id>\d+)/edit/$', views.volunteer_edit, name='volunteer_edit'),
)

volunteers/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import ugettext_lazy as _
from userena.models import UserenaLanguageBaseProfile

import datetime
# from dateutil import relativedelta
import hashlib
import httplib
import os
import urllib
import vobject
import xml.etree.ElementTree as ET


# Parse dates, times, DRY
def parse_datetime(date_str, format='%Y-%m-%d'):
    return datetime.datetime.strptime(date_str, format)


def parse_date(date_str, format='%Y-%m-%d'):
    return parse_datetime(date_str, format).date()


def parse_time(date_str, format='%H:%M'):
    return parse_datetime(date_str, format).time()


# More DRY: given a start hour and duration, return start and end time.
def parse_hour_duration(start_str, duration_str, format='%H:%M'):
    start = datetime.datetime.strptime(start_str, format)
    dur_tm = datetime.datetime.strptime(duration_str, format)
    duration = datetime.timedelta(hours=dur_tm.hour, minutes=dur_tm.minute, seconds=dur_tm.second)
    end = start + duration
    start_tm = datetime.time(hour=start.hour, minute=start.minute, second=start.second)
    end_tm = datetime.time(hour=end.hour, minute=end.minute, second=end.second)
    return(start_tm, end_tm)


# Helper model
class HasLinkField():
    def link(self):
        return 'Link'


# Create your models here.

class Edition(models.Model):
    class Meta:
        verbose_name = _('Edition')
        verbose_name_plural = _('Editions')
        ordering = ['-start_date']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=128)
    start_date = models.DateField()
    end_date = models.DateField()
    visible_from = models.DateField()
    visible_until = models.DateField()

    @classmethod
    def get_current(cls):
        retval = False
        today = datetime.date.today()
        current = cls.objects.filter(visible_from__lte=today, visible_until__gte=today)
        if current:
            retval = current[0].id
        return retval

    @classmethod
    def penta_create_or_update(cls, xml):
        ed_name = xml.find('title').text
        start_date = parse_date(xml.find('start').text)
        end_date = parse_date(xml.find('end').text)
        visible_from = datetime.date(year=start_date.year - 1, month=8, day=1)
        visible_until = datetime.date(year=start_date.year, month=7, day=31)
        editions = cls.objects.filter(name=ed_name)
        if len(editions):
            edition = editions[0]
        else:
            edition = cls(name=ed_name)  # create if required
        edition.start_date = start_date
        edition.end_date = end_date
        edition.visible_from = visible_from
        edition.visible_until = visible_until
        edition.save()
        return edition

    @classmethod
    def init_generic_tasks(cls):
        edition = cls.get_current()
        if edition:
            generic_task_tree = ET.parse(settings.GENERIC_TASKS_FILE)
            generic_task_root = generic_task_tree.getroot()
            for task in generic_task_root.findall('task'):
                Task.create_from_xml(task, edition)

    @classmethod
    def sync_with_penta(cls):
        penta_url = settings.SCHEDULE_SYNC_URI
        response = urllib.urlopen(penta_url)
        penta_xml = response.read()
        root = ET.fromstring(penta_xml)
        ###########
        # Edition #
        ###########
        ed = root.find('conference')
        edition = cls.penta_create_or_update(ed)

        #########
        # Talks #
        #########
        days = root.findall('day')
        for day in days:
            day_date = parse_date(day.get('date'))
            rooms = day.findall('room')
            for room in rooms:
                room_name = room.get('name')
                # Lightning talks are done manually since the time slots are so small.
                needs_heralding = room_name in settings.ROOMS_HERALDING_REQUIRED
                needs_video = room_name in settings.ROOMS_VIDEO_NEEDED
                events = room.findall('event')
                for event in events:
                    talk = Talk.penta_create_or_update(event, edition, day_date)
                    ######################
                    # Tasks, if required #
                    ######################
                    if needs_heralding:
                        Task.create_or_update_from_talk(edition, talk, 'Heralding', [3, 2, 5])
                    if needs_video:
                        Task.create_or_update_from_talk(edition, talk, 'Video', [1, 1, 1])


class Track(models.Model):
    """
    A track is a collection of talks, grouped around one single
    concept or subject.
    """
    class Meta:
        verbose_name = _('Track')
        verbose_name_plural = _('Tracks')
        ordering = ['date', 'start_time', 'title']

    def __unicode__(self):
        return self.title

    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    edition = models.ForeignKey(Edition, default=Edition.get_current)
    date = models.DateField()
    start_time = models.TimeField()
    # end_time = models.TimeField()


class Talk(models.Model, HasLinkField):
    class Meta:
        verbose_name = _('Talk')
        verbose_name_plural = _('Talks')
        ordering = ['date', 'start_time', '-end_time', 'title']

    def __unicode__(self):
        return self.title

    ext_id = models.CharField(max_length=16)  # ID from where we synchronise
    track = models.ForeignKey(Track)
    title = models.CharField(max_length=256)
    speaker = models.CharField(max_length=128)
    description = models.TextField()
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    volunteers = models.ManyToManyField('Volunteer', through='VolunteerTalk', blank=True, null=True)

    def assigned_volunteers(self):
        return self.volunteers.count()

    @classmethod
    def penta_create_or_update(cls, xml, edition, day_date):
        event_id = xml.get('id')
        talks = cls.objects.filter(ext_id=event_id)
        if len(talks):
            talk = talks[0]
        else:
            talk = cls(ext_id=event_id)
        start_txt = xml.find('start').text
        dur_txt = xml.find('duration').text
        (talk_start, talk_end) = parse_hour_duration(start_txt, dur_txt)
        track_name = xml.find('track').text
        tracks = Track.objects.filter(title=track_name, edition=edition)
        if len(tracks):
            track = tracks[0]
        else:
            track = Track(title=track_name, edition=edition, date=day_date, start_time=talk_start)
        if day_date < track.date:
            track.date = day_date
        if talk_start < track.start_time:
            track.start_time = talk_start
        track.save()
        talk.track = track
        talk.title = xml.find('title').text
        talk.description = xml.find('description').text or ''
        talk.date = day_date
        (talk.start_time, talk.end_time) = (talk_start, talk_end)
        persons = xml.find('persons')
        people = []
        if len(persons):
            for person in persons.findall('person'):
                people.append(person.text)
            speakers_str = ', '.join(people)
            talk.speaker = speakers_str
        talk.save()
        return talk


class TaskCategory(models.Model, HasLinkField):
    """
    Categories are things like buildup, cleanup, moderation, ...
    """
    class Meta:
        verbose_name = _('Task Category')
        verbose_name_plural = _('Task Categories')
        ordering = ['name']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=50)
    description = models.TextField()
    volunteers = models.ManyToManyField('Volunteer', through='VolunteerCategory', blank=True, null=True)
    active = models.BooleanField(default=True)

    def assigned_volunteers(self):
        return self.volunteer_set.count()

    @classmethod
    def create_or_update_named(cls, name):
        categories = TaskCategory.objects.filter(name=name)
        if len(categories):
            category = categories[0]
        else:
            category = cls(name=name)
            category.save()
        return category


class TaskTemplate(models.Model):
    """
    A task template contains all data about a task that isn't task specific.
    For example, cleanup can happen in multiple locations or at multiple times.
    Not sure we need this, but it seemed like a good thing to have when I wrote
    down the DB model. ;)
    """
    class Meta:
        verbose_name = _('Task Template')
        verbose_name_plural = _('Task Templates')
        ordering = ['name']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=50)
    description = models.TextField()
    category = models.ForeignKey(TaskCategory)

    @classmethod
    def create_or_update_named(cls, name):
        templates = cls.objects.filter(name=name)
        if len(templates):
            template = templates[0]
        else:
            template = cls(name=name)
            category = TaskCategory.create_or_update_named(name)
            template.category = category
            template.save()
        return template


class Task(models.Model, HasLinkField):
    """
    Contains the specifics of an instance of a task. It's based on a task
    template but can override the name and description, yet not the category.
    """
    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Tasks')
        ordering = ['date', 'start_time', '-end_time', 'name']

    def __unicode__(self):
        day = self.date.strftime('%a')
        start = self.start_time.strftime('%H:%M')
        end = self.end_time.strftime('%H:%M')

volunteers/forms.py
from volunteers.models import VolunteerTask, TaskCategory

from django import forms
from django.utils.translation import ugettext as _

from userena.models import UserenaSignup
from userena import settings as userena_settings
from userena.utils import get_profile_model, get_user_model

class AddTasksForm(forms.Form):
    tasks = forms.ModelMultipleChoiceField(queryset=VolunteerTask.objects.none(), widget=forms.CheckboxSelectMultiple())

class EditTasksForm(forms.Form):
    #do = forms.BooleanField(label=_(u'Do'), required=False)
    #nbr_volunteers = forms.IntegerField(label=_(u'Assigned volunteers'), required=True)
    date = forms.TimeField(label=_(u'Date'), required=True)
    start_time = forms.TimeField(label=_(u'Start time'), required=True)
    end_time = forms.TimeField(label=_(u'End time'), required=True)
    name = forms.CharField(label=_(u'Name'), max_length=30, required=True)
    description = forms.CharField(label=_(u'Description'), max_length=30, required=False, widget=forms.Textarea)

class SignupForm(forms.Form):
    """
        Form for creating a new user account.

        Validates that the requested username and e-mail is not already in use.
        Also requires the password to be entered twice.
    """
    USERNAME_RE = r'^[\.\w]+$'
    attrs_dict = {'class': 'required'}
    first_name = forms.CharField(max_length=30, required=True, label=_("First name"))
    last_name = forms.CharField(max_length=30, required=True, label=_("Last name"))
    username = forms.RegexField(regex=USERNAME_RE, max_length=30, widget=forms.TextInput(attrs=attrs_dict), label=_("Username"),
                                error_messages={'invalid': _('Username must contain only letters, numbers, dots and underscores.')})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, maxlength=75)), label=_("Email"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False), label=_("Create password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False), label=_("Repeat password"))

    def clean_username(self):
        """
            Validate that the username is alphanumeric and is not already in use.
            Also validates that the username is not listed in
            ``USERENA_FORBIDDEN_USERNAMES`` list.
        """
        try:
            user = get_user_model().objects.get(username__iexact=self.cleaned_data['username'])
        except get_user_model().DoesNotExist:
            pass
        else:
            if userena_settings.USERENA_ACTIVATION_REQUIRED and UserenaSignup.objects.filter(user__username__iexact=self.cleaned_data['username']).exclude(activation_key=userena_settings.USERENA_ACTIVATED):
                raise forms.ValidationError(_('This username is already taken but not confirmed. Please check your email for verification steps.'))
            raise forms.ValidationError(_('This username is already taken.'))
        if self.cleaned_data['username'].lower() in userena_settings.USERENA_FORBIDDEN_USERNAMES:
            raise forms.ValidationError(_('This username is not allowed.'))
        return self.cleaned_data['username']

    def clean_email(self):
        """ Validate that the e-mail address is unique. """
        if get_user_model().objects.filter(email__iexact=self.cleaned_data['email']):
            if userena_settings.USERENA_ACTIVATION_REQUIRED and UserenaSignup.objects.filter(user__email__iexact=self.cleaned_data['email']).exclude(activation_key=userena_settings.USERENA_ACTIVATED):
                raise forms.ValidationError(_('This email is already in use but not confirmed. Please check your email for verification steps.'))
            raise forms.ValidationError(_('This email is already in use. Please supply a different email.'))
        return self.cleaned_data['email']

    def clean(self):
        """
            Validates that the values entered into the two password fields match.
            Note that an error here will end up in ``non_field_errors()`` because
            it doesn't apply to a single field.
        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_('The two password fields didn\'t match.'))
        return self.cleaned_data

    def save(self):
        """ Creates a new user and account. Returns the newly created user. """

        first_name, last_name, username, email, password = (self.cleaned_data['first_name'],
                                                            self.cleaned_data['last_name'],
                                                            self.cleaned_data['username'],
                                                            self.cleaned_data['email'],
                                                            self.cleaned_data['password1'])

        new_user = UserenaSignup.objects.create_user(username, email, password,
                                                     not userena_settings.USERENA_ACTIVATION_REQUIRED,
                                                     userena_settings.USERENA_ACTIVATION_REQUIRED)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.save()
        return new_user

class EditProfileForm(forms.ModelForm):
    """ Base form used for fields that are always required """
    first_name = forms.CharField(label=_(u'First name'), max_length=30, required=True)
    last_name = forms.CharField(label=_(u'Last name'), max_length=30, required=True)

    # categories = forms.ModelMultipleChoiceField(label=_(u'Categories'), queryset=TaskCategory.objects.all(), \
    #     widget=forms.CheckboxSelectMultiple(), required=False, \
    #     help_text="""<br/><br/>
    #     Indicate your preference for which kind of tasks you'd prefer to do.
    #     The tasks belonging to this category will appear on top in the Tasks page, so you
    #     can find them easily.<br/><br/>
    #     Signing up for actual tasks does not happen here; that's done in the Tasks screen!""")

    def __init__(self, *args, **kw):
        super(EditProfileForm, self).__init__(*args, **kw)
        # Put the first and last name at the top
        new_order = self.fields.keyOrder[:-2]
        new_order.insert(0, 'first_name')
        new_order.insert(1, 'last_name')
        self.fields.keyOrder = new_order

    class Meta:
        model = get_profile_model()
        exclude = ['user', 'editions', 'tasks', 'signed_up', 'language', 'privacy', 'private_staff_rating', 'private_staff_notes', 'categories']

    def save(self, force_insert=False, force_update=False, commit=True):
        profile = super(EditProfileForm, self).save(commit=commit)
        # Save first and last name
        user = profile.user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

        return profile

volunteers/templates/volunteers/category_schedule_list.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Categories' %}</h2>{% endblock %}

{% block content %}
    {% for category, templates in categories.items %}
    <h2>Category: {{ category.name }}</h2>
    <ul>
        {% for template in templates %}

        <li><a href="{% url 'task_schedule' template.id %}" title="View Schedule">{{ template.name }}</a></li>
        {% endfor %}
    </ul>
    <br/>
    {% endfor %}
{% endblock %}

volunteers/templates/volunteers/talk_detailed.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Talk' %}</h2>{% endblock %}

{% block content %}
<form class="talk_list">{% csrf_token %}
    <fieldset>
        <legend class="talk_list">{% trans 'Talk' %}</legend>
        <table class="talk_list">
            <tr>
                <th width="20%">{% trans 'When' %}</th>
                <th width="40%">{% trans 'Title' %}</th>
                <th width="20%">{% trans 'Attending' %}</th>
            </tr>
            <tr>
                <td>{{ talk.date|date:"D" }}, {{ talk.start_time|time:"H:i" }} - {{ talk.end_time|time:"H:i" }}</td>
                <td>{{ talk.title }}</td>
                <td>
                {% for volunteer in talk.volunteers.all %}
                    {{ volunteer.user.first_name }} {{ volunteer.user.last_name }}, 
                {% endfor %}
            </tr>
        </table>
        <br>
    </fieldset>
</form>

<div id="dialog" title="Talk"></div>
{% endblock %}

volunteers/templates/volunteers/tasks.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Tasks' %}</h2>{% endblock %}

{% block content %}
{% if user.is_authenticated %}<a class="larger-font" href="{% url 'task_list_detailed' user.username %}" title="View schedule">View your schedule</a>{% endif %}
<form class="task_list" action="{% url 'task_list' %}" method="post">{% csrf_token %}
    {% if is_dr_manhattan %}
    <fieldset>
        <legend class="task_list">We seem to have a bit of a problem here...</legend><br/>
        <table>
            <tr>
                <td><img src="http://nighty.safehex.be/linked_pics/dr_manhattan.png"/></td>
                <td width="20px;">&nbsp;</td>
                <td style="vertical-align: top;">
                    Unless you look like the guy on the left, odds are you're not actually capable
                    of being in two different locations at the same time. So it might be wise to take
                    action on the tasks below...
                </td>
                <td width="50%">&nbsp;</td>
            </tr>
        </table><br/>
        <table class="task_list">
            <thead>
                <tr class="table_top_alert">
                    <th width="10%">{% trans "I'm in" %}!</th>
                    <th width="55%">{% trans 'Task' %}</th>
                    <th width="20%">{% trans 'When' %}</th>
                    <th width="15%">{% trans 'Volunteers' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for task_set in dr_manhattan_tasks %}
                    <tr class="task_set_alert">
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">Problematic tasks #{{ forloop.counter }}:</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                    </tr>
                    {% for task in task_set %}
                    <tr>
                        <td {% if user.is_authenticated %}data-title="{% trans 'I am in' %}!"{% endif %}>{% if user.is_authenticated %}<input type="checkbox" name="task" value="{{ task.id }}" {{ checked|get_item:task.id }} />{% endif %}</td>
                        {% if attending|get_item:task.id == True %}
                        <td class="task-name special-task">{{ task.name }} <span class="small_note">(Hey, you're attending this!)</span></td>
                        {% else %}
                        <td data-title="{% trans 'Task' %}" class="task-name"><a href="{% url 'task_detailed' task.id %}">{{ task.name }}</a></td>
                        {% endif %}
                        <td data-title="{% trans 'When' %}" >{{ task.date|date:"D" }}, {{ task.start_time|time:"H:i" }} - {{ task.end_time|time:"H:i" }}</td>
                        {% if task.assigned_volunteers == task.nbr_volunteers_max %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers blue" title="{% trans 'Full' %}
                        {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                        {% elif task.assigned_volunteers >= task.nbr_volunteers %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers green" title="{% trans 'Staffed' %}
                        {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                        {% elif task.assigned_volunteers >= task.nbr_volunteers_min %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers gray" title="{% trans 'Manageable' %}
                        {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                        {% else %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers red" title="{% trans 'More volunteers needed' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %} {% endif%}">
                        {% endif %}
                        {{task.assigned_volunteers}}/{{ task.nbr_volunteers }}</td>
                    </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </fieldset>
    {% endif %}
    {% for title, days in tasks.items %}
    <fieldset>
        <legend class="task_list">{% trans title %} <span style="font-size: small; font-weight: normal;">
            {% if user.is_authenticated %}{% if title == 'preferred tasks' %}
            (<a class="larger-font" href="{% url 'userena_profile_edit' user.username %}">{% trans 'Change in profile' %}</a>)
            {% endif %}{% endif %}
        </span></legend>
        <table class="task_list">
            <thead>
                <tr class="table_top">
                    <th width="10%">{% trans "I'm in" %}!</th>
                    <th width="55%">{% trans 'Task' %}</th>
                    <th width="20%">{% trans 'When' %}</th>
                    <th width="15%">{% trans 'Volunteers' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for day, categories in days.items %}
                {% if categories.items %}
                {% ifchanged %}
                {% else %}
                <tr class="row-hide">
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                </tr>
                {% endifchanged %}
                <tr class="day">
                    <th class="no_vert_border">{{ day|date:"l" }}</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                </tr>
                    {% for category, category_tasks in categories.items %}
                    {% if category_tasks %}
                    {% ifchanged %}
                    {% else %}
                    <tr class="row-hide">
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                    </tr>
                    {% endifchanged %}
                    <tr class="category">
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">{{ category.name }}</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                    </tr>
                        {% for task in category_tasks %}
                        <tr>
                            <td {% if user.is_authenticated %}data-title="{% trans 'I am in' %}!"{% endif %}>{% if user.is_authenticated %}<input type="checkbox" name="task" value="{{ task.id }}" {{ checked|get_item:task.id }} />{% endif %}</td>
                            {% if attending|get_item:task.id == True %}
                            <td class="task-name special-task">{{ task.name }} <span class="small_note">(Hey, you're attending this!)</span></td>
                            {% else %}
                            <td data-title="{% trans 'Task' %}" class="task-name"><a href="{% url 'task_detailed' task.id %}">{{ task.name }}</a></td>
                            {% endif %}
                            <td data-title="{% trans 'When' %}">{{ task.date|date:"D" }}, {{ task.start_time|time:"H:i" }} - {{ task.end_time|time:"H:i" }}</td>
                            {% if task.assigned_volunteers == task.nbr_volunteers_max %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers blue" title="{% trans 'Full' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% elif task.assigned_volunteers >= task.nbr_volunteers %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers green" title="{% trans 'Staffed' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% elif task.assigned_volunteers >= task.nbr_volunteers_min %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers gray" title="{% trans 'Manageable' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% else %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers red" title="{% trans 'More volunteers needed' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% endif %}
                            {{task.assigned_volunteers}}/{{ task.nbr_volunteers }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        <br>
    </fieldset>
    {% endfor %}
    {% if user.is_authenticated %}
    <input type="submit" value="{% trans "Save changes" %}" />
    {% endif %}
</form>

<div id="dialog" title="Task"></div>

{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
        {% endif %}

        <span class="current">
            {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}